run: # https://golangci-lint.run/usage/configuration/
  timeout: 3m

# all available settings of specific linters
linters-settings:
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        deny:
          - pkg: "github.com/golang/protobuf"
            desc: Superseded by google.golang.org/protobuf
          - pkg: "errors"
            desc: Should be replaced by github.com/pkg/errors
      Test:
        files:
          - $test
        deny:
          - pkg: "github.com/golang/protobuf"
            desc: Superseded by google.golang.org/protobuf
          - pkg: "errors"
            desc: Should be replaced by github.com/pkg/errors
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  exhaustive:
    default-signifies-exhaustive: true
  varnamelen:
    min-name-length: 2
  wsl:
    allow-cuddle-declarations: true
    allow-assign-and-anything: true
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake

linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - gomnd # deprecated
    - exhaustruct # too much unnecessary verbosity
    - gci # already used goimports
    - testpackage
    - wrapcheck # this seems to be a false positive
    - ireturn # too annoying
    - nonamedreturns # too annoying

output:
  sort-results: true

issues:
  exclude:
    - "should have comment or be unexported"
    - "should have a package comment"
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - funlen
        - protogetter
        - stylecheck
        - gocyclo