services:
  wait:
    container_name: wait
    image: dokku/wait:latest
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: wait
      com.vnworkday.docker.project: vnworkday
    restart: no
    depends_on:
      swag:
        condition: service_healthy