services:
  pre-commit:
    container_name: pre-commit
    build:
      context: ..
      dockerfile: ci/Dockerfile
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: pre-commit
      com.vnworkday.docker.project: vnworkday
    restart: always
    entrypoint: /bin/sh
    stdin_open: true
    stop_signal: SIGKILL
    healthcheck:
      test: [ "CMD", "pre-commit", "--version" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
  wait:
    container_name: wait
    image: dokku/wait:latest
    pull_policy: missing
    labels:
      com.vnworkday.docker.name: wait
      com.vnworkday.docker.project: vnworkday
    restart: no
    depends_on:
      pre-commit:
        condition: service_healthy