basePath: /api/v1
definitions:
  accountmodel.Tenant:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: ntduy.cs@gmail.com
    name: Duy Nguyen
    url: https://github.com/vnworkday/gateway
  description: This is the API documentation for VN Workday Gateway API.
  title: VN Workday Gateway API
  version: 0.1.0
paths:
  /tenants:
    get:
      description: List all tenants
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accountmodel.Tenant'
      summary: List all tenants
      tags:
      - Tenant
  /tenants/{id}:
    get:
      description: Get a tenant by ID
      parameters:
      - description: Tenant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/accountmodel.Tenant'
      summary: Get a tenant by ID
      tags:
      - Tenant
schemes:
- http
- https
swagger: "2.0"
